SHELL=/bin/bash
.DEFAULT_GOAL := help

# https://gist.github.com/tadashi-aikawa/da73d277a3c1ec6767ed48d1335900f3
.PHONY: $(shell grep --no-filename -E '^[a-zA-Z0-9_-]+:' $(MAKEFILE_LIST) | sed 's/://')

# Phony Targets
all: fmt clean-test vet ## Format, Clean and Test

clean-test: clean test ## Clean and Test

test: fmt ## Test
	go test ./...

vet: ## Vet
	go vet ./...

fmt: ## Format
	go fmt ./...

clean: ## Clean
	go clean -cache -testcache

linefeed: ## Convert linefeed
	sed -i '' 's/\r//' Fixture/Manual/Main.jack

# https://postd.cc/auto-documented-makefile/
help: ## Show help
	@grep --no-filename -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-40s\033[0m %s\n", $$1, $$2}'
